openapi: 3.0.0
info:
  title: API de Produtos
  description: API para gerenciamento de produtos com Fiber e PostgreSQL
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Servidor local

paths:
  /products:
    get:
      summary: Lista todos os produtos
      responses:
        '200':
          description: Lista de produtos retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Cria um novo produto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '201':
          description: Produto criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /products/{id}:
    get:
      summary: Obtém um produto específico
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID do produto
      responses:
        '200':
          description: Produto retornado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Produto não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    put:
      summary: Atualiza um produto existente
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID do produto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '200':
          description: Produto atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Produto não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Deleta um produto
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID do produto
      responses:
        '204':
          description: Produto deletado com sucesso
        '500':
          description: Erro ao deletar produto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          description: ID único do produto
        name:
          type: string
          description: Nome do produto
        description:
          type: string
          description: Descrição do produto
        price:
          type: number
          format: float
          description: Preço do produto
        stock:
          type: integer
          description: Quantidade em estoque
        created_at:
          type: string
          description: Data de criação do produto
      required:
        - name
        - description
        - price
        - stock

    ProductInput:
      type: object
      properties:
        name:
          type: string
          description: Nome do produto
        description:
          type: string
          description: Descrição do produto
        price:
          type: number
          format: float
          description: Preço do produto
        stock:
          type: integer
          description: Quantidade em estoque
      required:
        - name
        - description
        - price
        - stock

    Error:
      type: object
      properties:
        error:
          type: string
          description: Mensagem de erro
      required:
        - error